AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Gateway to Kinesis Data Stream to AWS Lambda

Resources:
  # Define REST API for Kinesis data streams using OpenAPI3.0
  KinesisProxy2:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      EndpointConfiguration:
        Type: REGIONAL
      TracingEnabled: true
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./src/api/api.yaml
  
  # Define an AWS Kinesis Data Stream
  MyStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 2
      Name: KinesisStream
  
  # Define an AWS Lambda and attach it to the application consumer
  ApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Runtime: python3.8
      Handler: app.lambda_Handler
      Tracing: Active
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt MyStream.Arn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
            
Outputs:
  # Kinesis Data Stream name for data producers to use
  KinesisStream:
    Description: Kinesis Data Stream name
    Value: !Ref MyStream
