AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Gateway to Kinesis Data Stream to AWS Lambda

# This template builds integration between API Gateway, Kinesis data streams and AWS Lambda

Globals:
  Function:
    MemorySize: 2048
    Timeout: 15

Resources:
  # Define REST API for Kinesis data streams using OpenAPI3.0
  KinesisProxyApi:
    Type: AWS::Serverless::Api
    DependsOn: ApiKinesisExecutionRole
    Properties:
      StageName: dev
      EndpointConfiguration:
        Type: REGIONAL
      TracingEnabled: true
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./src/api/api.yaml
      

  # Define AWS Kinesis Data Stream
  MyKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 2
      Name: MyStream
  
  ApiKinesisExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
        - arn:aws:iam::aws:policy/AmazonKinesisFullAccess

  # Define an AWS Lambda and attach it to the application consumer
  ApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Handler for Lambda function that process Kinesis data streams
      CodeUri: src/
      Runtime: python3.8
      Handler: app.lambda_Handler
      Tracing: Active
      FunctionName: MyKDSFunction
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt MyKinesisStream.Arn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      BucketName: serverless-capstone
    DeletionPolicy: Retain
  
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
      Bucket: !Ref S3Bucket
    
Outputs:
  # Kinesis Data Stream name for data producers to use
  KinesisStream:
    Description: Kinesis Data Stream name
    Value: !Ref MyKinesisStream
    
  APIEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${KinesisProxyApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
    
  WebsiteURL:
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content